services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      MONGODB_URI: mongodb://mongo_db:27017
      PORT: 3000
      DB_NAME: dbLib
    depends_on:
      - mongo_db
    command: npm start
  tests:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://mongo_db:27017
      PORT: 3000
      DB_NAME: dbLib
    depends_on:
      - mongo_db
    command: npm test
  
volumes:
  mongo_db: {}
